apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-api-2
      tier: back
  template:
    metadata:
      labels:
        app: test-api-2
        tier: back
    spec:
      containers:
        - name: test-api
          image: public.ecr.aws/p4g1u1f9/23724-k8s/api:13
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: test-api-2
spec:
  selector:
    app: test-api
    tier: back
  ports:
    - port: 8082

